services:
   server:
      container_name: mentorshub_server
      build:
         context: .
         dockerfile: Dockerfile
      restart: always
      env_file:
         - .env
      environment:
         - NODE_ENV=development
      ports:
         - "5858:5858"
      volumes:
         - /app/node_modules
      networks:
         - app-network

   nginx:
      image: nginx:alpine
      container_name: mentorshub_nginx_proxy
      restart: always
      ports:
         - "80:80"
         - "443:443"
      volumes:
         - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
         - ./nginx/certs:/etc/ssl/certs:ro   # mount certs folder
      depends_on:
         - server
      networks:
         - app-network

networks:
   app-network:
      driver: bridge
