services:
   server:
      container_name: mentorshub_server
      image: jasimihsan9656/mentorshub-backend:latest
      platform: linux/amd64
      pull_policy: always
      build:
         context: .
         dockerfile: Dockerfile.prod
      restart: always
      # env_file:
      #    - .env
      environment:
         - NODE_ENV=production
      volumes:
         - /app/node_modules

   nginx:
      image: nginx:alpine
      container_name: mentorshub_nginx_proxy
      restart: always
      ports:
         - "80:80"
         - "443:443"
      volumes:
         - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
         - /etc/letsencrypt/live/mentorshub.ddns.net/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
         - /etc/letsencrypt/live/mentorshub.ddns.net/privkey.pem:/etc/ssl/private/privkey.pem:ro
      depends_on:
         - server
