import { cloudinaryService, mentorRepository, rescheduleRequestRepository, s3BucketService, sessionRepository, specialAvailabilityRepository, userRepository, walletRepository, weeklyAvailabilityRepository } from "../../../infrastructure/composer";
import { UploadMentorDocumentUseCase } from "../documents/upload.mentor.document.usecase";
import { updateUserTaskProgressUseCase } from "../gamification/composer";
import { notifyUserUseCase } from "../notification/composer";
import { GetAvailabilityUseCase } from "./get.mentor.availability.usecase";
import { GetSessionHistoryUsecase } from "./session/get.session.history.usecase";
import { GetSessionRescheduleRequestsByMentorUseCase } from "./session/get.session.reschedule.requests.by.mentor.usecase";
import { GetUpcomingSessionMentorUsecase } from "./session/get.upcoming.sessions.usecase";
import { GetAllApprovedMentorsUsecase } from "./getAllApprovedMentors.usecase";
import { GetAllMentorsUseCase } from "./getAllMentors.usecase";
import { GetMentorUsecase } from "./getMentor.usecase";
import { GetSessionRequests } from "./session/getSessionRequests.usecase";
import { UpdateMentorProfileUseCase } from "./update.mentor.profile.usecase";
import { UpdateSessionStatusUsecase } from "./update.status.usecase";
import { ReleaseSessionFundsUseCase } from "./session/release.session.fund.usecase";
import { CancelSessionByMentorUseCase } from "./session/cancel.session.by.mentor.usecase";
import { mentorCancelSessionRefundUseCase } from "../refund/composer";

const uploadMentorDocumentUseCase = new UploadMentorDocumentUseCase(s3BucketService);

export const getAllMentorsUsecase = new GetAllMentorsUseCase(mentorRepository);
export const releaseSessionFundsUseCase = new ReleaseSessionFundsUseCase(sessionRepository, walletRepository, notifyUserUseCase);
export const getAllApprovedMentorsUsecase = new GetAllApprovedMentorsUsecase(mentorRepository);
export const getMentorUsecase = new GetMentorUsecase(mentorRepository);
export const getRequestUsecase = new GetSessionRequests(sessionRepository);
export const getUpcomingSessionMentorUsecase = new GetUpcomingSessionMentorUsecase(sessionRepository, rescheduleRequestRepository);
export const getSessionHistoryUsecase = new GetSessionHistoryUsecase(sessionRepository);
export const getAvailabilityUsecase = new GetAvailabilityUseCase(sessionRepository, weeklyAvailabilityRepository, specialAvailabilityRepository);
export const updateMentorProfileUseCase = new UpdateMentorProfileUseCase(mentorRepository, userRepository, uploadMentorDocumentUseCase, notifyUserUseCase, cloudinaryService);
export const updateSessionStatusUsecase = new UpdateSessionStatusUsecase(sessionRepository, updateUserTaskProgressUseCase, userRepository, notifyUserUseCase, getAvailabilityUsecase, releaseSessionFundsUseCase);
export const getSessionRescheduleRequestsByMentorUseCase = new GetSessionRescheduleRequestsByMentorUseCase(rescheduleRequestRepository, sessionRepository);
export const cancelSessionByMentorUseCase = new CancelSessionByMentorUseCase(sessionRepository, rescheduleRequestRepository, mentorCancelSessionRefundUseCase, notifyUserUseCase);
