import { Option } from "@/components/ui/multiple-selector";

export const SKILL_OPTIONS: Option[] = [
	{ label: "JavaScript", value: "javascript" },
	{ label: "React", value: "react" },
	{ label: "Python", value: "python" },
	{ label: "CSS", value: "css" },
	{ label: "Node.js", value: "nodejs" },
	{ label: "TypeScript", value: "typescript" },
	{ label: "HTML", value: "html" },
	{ label: "Content Creation", value: "content-creation" },
	{ label: "Mobile App Development", value: "mobile-app-development" },
	{ label: "Branding", value: "branding" },
	{ label: "Artificial Intelligence", value: "artificial-intelligence" },
	{ label: "Blockchain Technology", value: "blockchain-technology" },
	{ label: "Quantum Computing", value: "quantum-computing" },
	{ label: "Game Design", value: "game-design" },
	{ label: "Graphic Design", value: "graphic-design" },
	{ label: "Photography", value: "photography" },
	{ label: "Bioinformatics", value: "bioinformatics" },
	{ label: "Video Editing", value: "video-editing" },
	{ label: "Gardening", value: "gardening" },
	{ label: "Personal Training", value: "personal-training" },
	{ label: "Public Speaking", value: "public-speaking" },
	{ label: "Mixology", value: "mixology" },
	{ label: "E-commerce", value: "e-commerce" },
	{ label: "Robotics", value: "robotics" },
	{ label: "Data Analysis", value: "data-analysis" },
	{ label: "UI/UX Design", value: "ui-ux-design" },
	{ label: "Interior Decorating", value: "interior-decorating" },
	{ label: "Customer Service", value: "customer-service" },
	{ label: "Meditation", value: "meditation" },
	{ label: "Green Energy", value: "green-energy" },
	{ label: "Sales", value: "sales" },
	{ label: "Presentation", value: "presentation" },
	{ label: "DIY Crafting", value: "diy-crafting" },
	{ label: "Risk Assessment", value: "risk-assessment" },
	{ label: "Financial Analysis", value: "financial-analysis" },
	{ label: "Problem Solving", value: "problem-solving" },
	{ label: "Training", value: "training" },
	{ label: "Research", value: "research" },
	{ label: "Conflict Resolution", value: "conflict-resolution" },
	{ label: "Baking", value: "baking" },
	{ label: "Cybersecurity", value: "cybersecurity" },
	{ label: "Market Research", value: "market-research" },
	{ label: "Leadership", value: "leadership" },
	{ label: "Design", value: "design" },
	{ label: "Critical Thinking", value: "critical-thinking" },
	{ label: "Accounting", value: "accounting" },
	{ label: "Virtual Reality", value: "virtual-reality" },
	{ label: "Networking", value: "networking" },
	{ label: "Augmented Reality", value: "augmented-reality" },
	{ label: "Pilates", value: "pilates" },
	{ label: "Negotiation", value: "negotiation" },
	{ label: "Time Management", value: "time-management" },
	{ label: "Animation", value: "animation" },
	{ label: "Contract Negotiation", value: "contract-negotiation" },
	{ label: "Empathy", value: "empathy" },
	{ label: "Digital Marketing", value: "digital-marketing" },
	{ label: "Decision Making", value: "decision-making" },
	{ label: "Foreign Languages", value: "foreign-languages" },
	{ label: "Public Relations", value: "public-relations" },
	{ label: "Communication", value: "communication" },
	{ label: "Adaptability", value: "adaptability" },
	{ label: "Coding", value: "coding" },
	{ label: "Creativity", value: "creativity" },
	{ label: "Web Development", value: "web-development" },
	{ label: "Nanotechnology", value: "nanotechnology" },
	{ label: "Medical Coding", value: "medical-coding" },
	{ label: "Music Production", value: "music-production" },
	{ label: "Quality Assurance", value: "quality-assurance" },
	{ label: "Email Marketing", value: "email-marketing" },
	{ label: "Strategic Planning", value: "strategic-planning" },
	{ label: "Community Development", value: "community-development" },
	{ label: "Woodworking", value: "woodworking" },
	{ label: "Pottery", value: "pottery" },
	{ label: "Sewing", value: "sewing" },
	{ label: "Automotive Repair", value: "automotive-repair" },
	{ label: "Electrical Engineering", value: "electrical-engineering" },
	{ label: "Civil Engineering", value: "civil-engineering" },
	{ label: "Mechanical Engineering", value: "mechanical-engineering" },
	{ label: "Astronomy", value: "astronomy" },
	{ label: "Archaeology", value: "archaeology" },
	{ label: "Event Planning", value: "event-planning" },
	{ label: "Journalism", value: "journalism" },
	{ label: "Copywriting", value: "copywriting" },
	{ label: "Translation", value: "translation" },
	{ label: "Scuba Diving", value: "scuba-diving" },
	{ label: "Skydiving", value: "skydiving" },
	{ label: "Mountaineering", value: "mountaineering" },
	{ label: "Carpentry", value: "carpentry" },
	{ label: "Welding", value: "welding" },
	{ label: "Plumbing", value: "plumbing" },
	{ label: "Ethical Hacking", value: "ethical-hacking" },
	{ label: "Forensic Science", value: "forensic-science" },
	{ label: "Urban Planning", value: "urban-planning" },
	{ label: "Supply Chain Management", value: "supply-chain-management" },
	{ label: "Project Management", value: "project-management" },
	{ label: "Genetic Engineering", value: "genetic-engineering" },
	{ label: "Meteorology", value: "meteorology" },
	{ label: "Oceanography", value: "oceanography" },
	{ label: "Paleontology", value: "paleontology" },
	{ label: "Scriptwriting", value: "scriptwriting" },
	{ label: "Voice Acting", value: "voice-acting" },
	{ label: "Choreography", value: "choreography" },
	{ label: "Fashion Design", value: "fashion-design" },
	{ label: "Makeup Artistry", value: "makeup-artistry" },
	{ label: "Tattoo Artistry", value: "tattoo-artistry" },
	{ label: "Calligraphy", value: "calligraphy" },
	{ label: "Leatherworking", value: "leatherworking" },
	{ label: "Glassblowing", value: "glassblowing" },
	{ label: "Jewelry Making", value: "jewelry-making" },
	{ label: "Sommelier (Wine Expertise)", value: "sommelier-wine-expertise" },
	{ label: "Barista Skills", value: "barista-skills" },
	{ label: "Animal Training", value: "animal-training" },
	{ label: "Veterinary Medicine", value: "veterinary-medicine" },
	{ label: "Herbalism", value: "herbalism" },
	{ label: "Acupuncture", value: "acupuncture" },
	{ label: "Massage Therapy", value: "massage-therapy" },
	{ label: "Nutrition Consulting", value: "nutrition-consulting" },
	{ label: "3D Printing", value: "3d-printing" },
	{ label: "Drone Piloting", value: "drone-piloting" },
	{ label: "Satellite Engineering", value: "satellite-engineering" },
	{ label: "Machine Learning", value: "machine-learning" },
	{ label: "Deep Learning", value: "deep-learning" },
	{ label: "Cloud Computing", value: "cloud-computing" },
	{ label: "DevOps", value: "devops" },
	{ label: "Search Engine Optimization (SEO)", value: "search-engine-optimization-seo" },
	{ label: "Social Media Management", value: "social-media-management" },
	{ label: "Grant Writing", value: "grant-writing" },
	{ label: "Fundraising", value: "fundraising" },
	{ label: "Policy Analysis", value: "policy-analysis" },
	{ label: "Logistics", value: "logistics" },
	{ label: "Tax Preparation", value: "tax-preparation" },
	{ label: "Real Estate Appraisal", value: "real-estate-appraisal" },
	{ label: "Property Management", value: "property-management" },
	{ label: "Horticulture", value: "horticulture" },
	{ label: "Entomology (Study of Insects)", value: "entomology-study-of-insects" },
	{ label: "Mycology (Study of Fungi)", value: "mycology-study-of-fungi" },
	{ label: "Sound Engineering", value: "sound-engineering" },
	{ label: "Lighting Design", value: "lighting-design" },
	{ label: "Stage Management", value: "stage-management" },
	{ label: "Costume Design", value: "costume-design" },
	{ label: "Puppetry", value: "puppetry" },
	{ label: "Ventriloquism", value: "ventriloquism" },
	{ label: "Storytelling", value: "storytelling" },
	{ label: "Improvisation", value: "improvisation" },
	{ label: "Stand-up Comedy", value: "stand-up-comedy" },
	{ label: "Sports Coaching", value: "sports-coaching" },
	{ label: "Refereeing", value: "refereeing" },
	{ label: "Wilderness Survival", value: "wilderness-survival" },
	{ label: "Navigation", value: "navigation" },
	{ label: "Cartography (Map-making)", value: "cartography-map-making" },
	{ label: "Typography", value: "typography" },
	{ label: "Illustration", value: "illustration" },
	{ label: "Stop-motion Animation", value: "stop-motion-animation" },
	{ label: "Game Programming", value: "game-programming" },
	{ label: "Ethical Sourcing", value: "ethical-sourcing" },
	{ label: "Sustainability Consulting", value: "sustainability-consulting" },
	{ label: "Renewable Energy Engineering", value: "renewable-energy-engineering" },
	{ label: "Chemical Engineering", value: "chemical-engineering" },
	{ label: "Materials Science", value: "materials-science" },
	{ label: "Anthropology", value: "anthropology" },
	{ label: "Sociology", value: "sociology" },
	{ label: "Psychology", value: "psychology" },
	{ label: "Counseling", value: "counseling" },
	{ label: "Life Coaching", value: "life-coaching" },
	{ label: "Motivational Speaking", value: "motivational-speaking" },
	{ label: "Locksmithing", value: "locksmithing" },
	{ label: "Upholstery", value: "upholstery" },
	{ label: "Bookbinding", value: "bookbinding" },
	{ label: "Taxidermy", value: "taxidermy" },
	{ label: "Beekeeping", value: "beekeeping" },
	{ label: "Falconry", value: "falconry" },
	{ label: "Horse Training", value: "horse-training" },
	{ label: "Sailing", value: "sailing" },
	{ label: "Fishing", value: "fishing" },
	{ label: "Brewing (Beer Making)", value: "brewing-beer-making" },
	{ label: "Winemaking", value: "winemaking" },
	{ label: "Cheese Making", value: "cheese-making" },
	{ label: "Candle Making", value: "candle-making" },
	{ label: "Soap Making", value: "soap-making" },
	{ label: "Perfumery", value: "perfumery" },
	{ label: "Origami", value: "origami" },
	{ label: "Knitting", value: "knitting" },
	{ label: "Crocheting", value: "crocheting" },
	{ label: "Embroidery", value: "embroidery" },
	{ label: "Quilting", value: "quilting" },
	{ label: "Stained Glass Art", value: "stained-glass-art" },
	{ label: "Mural Painting", value: "mural-painting" },
	{ label: "Sculpting", value: "sculpting" },
	{ label: "Metalworking", value: "metalworking" },
	{ label: "Blacksmithing", value: "blacksmithing" },
	{ label: "Silversmithing", value: "silversmithing" },
	{ label: "Gem Cutting", value: "gem-cutting" },
	{ label: "Watchmaking", value: "watchmaking" },
	{ label: "Clock Repair", value: "clock-repair" },
	{ label: "Bicycle Repair", value: "bicycle-repair" },
	{ label: "Aviation Mechanics", value: "aviation-mechanics" },
	{ label: "Flight Instruction", value: "flight-instruction" },
	{ label: "Air Traffic Control", value: "air-traffic-control" },
	{ label: "Maritime Navigation", value: "maritime-navigation" },
	{ label: "Shipbuilding", value: "shipbuilding" },
	{ label: "Hydrology (Water Science)", value: "hydrology-water-science" },
	{ label: "Geology", value: "geology" },
	{ label: "Seismology", value: "seismology" },
	{ label: "Volcanology", value: "volcanology" },
	{ label: "Biophysics", value: "biophysics" },
	{ label: "Astrophysics", value: "astrophysics" },
	{ label: "Particle Physics", value: "particle-physics" },
	{ label: "Nuclear Engineering", value: "nuclear-engineering" },
	{ label: "Photonics (Light-based Technology)", value: "photonics-light-based-technology" },
	{ label: "Cryptography", value: "cryptography" },
	{ label: "Stenography", value: "stenography" },
	{ label: "Sign Language Interpretation", value: "sign-language-interpretation" },
	{ label: "Dialect Coaching", value: "dialect-coaching" },
	{ label: "Phonetics", value: "phonetics" },
	{ label: "Lexicography (Dictionary Making)", value: "lexicography-dictionary-making" },
	{ label: "Archival Science", value: "archival-science" },
	{ label: "Museum Curation", value: "museum-curation" },
	{ label: "Art Restoration", value: "art-restoration" },
	{ label: "Historical Reenactment", value: "historical-reenactment" },
	{ label: "Genealogy", value: "genealogy" },
	{ label: "Heraldry (Coat of Arms Design)", value: "heraldry-coat-of-arms-design" },
	{ label: "Auctioneering", value: "auctioneering" },
	{ label: "Appraisal (Antiques/Collectibles)", value: "appraisal-antiques-collectibles" },
	{ label: "Tour Guiding", value: "tour-guiding" },
	{ label: "Travel Planning", value: "travel-planning" },
	{ label: "Cultural Anthropology", value: "cultural-anthropology" },
	{ label: "Ethnomusicology", value: "ethnomusicology" },
	{ label: "Folklore Studies", value: "folklore-studies" },
	{ label: "Philosophy", value: "philosophy" },
	{ label: "Theology", value: "theology" },
	{ label: "Debate", value: "debate" },
	{ label: "Arbitration", value: "arbitration" },
	{ label: "Mediation", value: "mediation" },
	{ label: "Patent Law", value: "patent-law" },
	{ label: "Trademark Law", value: "trademark-law" },
	{ label: "Paralegal Skills", value: "paralegal-skills" },
	{ label: "Investigative Journalism", value: "investigative-journalism" },
	{ label: "Photojournalism", value: "photojournalism" },
	{ label: "Wildlife Photography", value: "wildlife-photography" },
	{ label: "Astrophotography", value: "astrophotography" },
	{ label: "Macro Photography", value: "macro-photography" },
	{ label: "Underwater Photography", value: "underwater-photography" },
	{ label: "Sound Design", value: "sound-design" },
	{ label: "Foley Artistry (Sound Effects)", value: "foley-artistry-sound-effects" },
	{ label: "Radio Production", value: "radio-production" },
	{ label: "Podcasting", value: "podcasting" },
	{ label: "Voiceover Work", value: "voiceover-work" },
	{ label: "Circus Performance (e.g., Juggling, Trapeze)", value: "circus-performance-juggling-trapeze" },
	{ label: "Magic/Illusion", value: "magic-illusion" },
	{ label: "Pyrotechnics (Fireworks Design)", value: "pyrotechnics-fireworks-design" },
	{ label: "Ice Sculpting", value: "ice-sculpting" },
	{ label: "Sand Sculpting", value: "sand-sculpting" },
	{ label: "Kite Making", value: "kite-making" },
	{ label: "Model Building (e.g., Trains, Planes)", value: "model-building-trains-planes" },
	{ label: "Miniature Painting", value: "miniature-painting" },
	{ label: "Bonsai Cultivation", value: "bonsai-cultivation" },
	{ label: "Topiary (Plant Sculpting)", value: "topiary-plant-sculpting" },
	{ label: "Aquascaping (Aquarium Design)", value: "aquascaping-aquarium-design" },
	{ label: "Terrarium Design", value: "terrarium-design" },
	{ label: "Dog Grooming", value: "dog-grooming" },
	{ label: "Pet Psychology", value: "pet-psychology" },
	{ label: "Exotic Animal Care", value: "exotic-animal-care" },
	{ label: "Ornithology (Bird Study)", value: "ornithology-bird-study" },
	{ label: "Herpetology (Reptile/Amphibian Study)", value: "herpetology-reptile-amphibian-study" },
	{ label: "Marine Biology", value: "marine-biology" },
	{ label: "Limnology (Study of Freshwater Systems)", value: "limnology-study-of-freshwater-systems" },
	{ label: "Soil Science", value: "soil-science" },
	{ label: "Viticulture (Grape Growing)", value: "viticulture-grape-growing" },
	{ label: "Oenology (Wine Science)", value: "oenology-wine-science" },
	{ label: "Food Styling", value: "food-styling" },
	{ label: "Pastry Arts", value: "pastry-arts" },
	{ label: "Butchery", value: "butchery" },
	{ label: "Charcuterie (Cured Meats)", value: "charcuterie-cured-meats" },
	{ label: "Molecular Gastronomy", value: "molecular-gastronomy" },
	{ label: "Fermentation (e.g., Kombucha, Kimchi)", value: "fermentation-kombucha-kimchi" },
	{ label: "Adobe Photoshop", value: "adobe-photoshop" },
	{ label: "Adobe Illustrator", value: "adobe-illustrator" },
	{ label: "Adobe InDesign", value: "adobe-indesign" },
	{ label: "Adobe Premiere Pro", value: "adobe-premiere-pro" },
	{ label: "Adobe After Effects", value: "adobe-after-effects" },
	{ label: "AutoCAD", value: "autocad" },
	{ label: "SolidWorks", value: "solidworks" },
	{ label: "MATLAB", value: "matlab" },
	{ label: "Tableau", value: "tableau" },
	{ label: "Power BI", value: "power-bi" },
	{ label: "Microsoft Excel (Advanced, e.g., VBA, Macros)", value: "microsoft-excel-advanced-vba-macros" },
	{ label: "Microsoft PowerPoint (Advanced Design)", value: "microsoft-powerpoint-advanced-design" },
	{ label: "Microsoft Dynamics 365", value: "microsoft-dynamics-365" },
	{ label: "SAP (e.g., ERP, HANA)", value: "sap-erp-hana" },
	{ label: "Oracle Database", value: "oracle-database" },
	{ label: "SQL Server", value: "sql-server" },
	{ label: "MySQL", value: "mysql" },
	{ label: "PostgreSQL", value: "postgresql" },
	{ label: "MongoDB", value: "mongodb" },
	{ label: "Python (with Libraries like Pandas, NumPy)", value: "python-pandas-numpy" },
	{ label: "R (Statistical Programming)", value: "r-statistical-programming" },
	{ label: "TensorFlow", value: "tensorflow" },
	{ label: "PyTorch", value: "pytorch" },
	{ label: "Unity (Game Development)", value: "unity-game-development" },
	{ label: "Unreal Engine", value: "unreal-engine" },
	{ label: "Blender (3D Modeling/Animation)", value: "blender-3d-modeling-animation" },
	{ label: "SketchUp", value: "sketchup" },
	{ label: "Revit (BIM Software)", value: "revit-bim-software" },
	{ label: "ArcGIS (Geospatial Analysis)", value: "arcgis-geospatial-analysis" },
	{ label: "QGIS", value: "qgis" },
	{ label: "ANSYS (Engineering Simulation)", value: "ansys-engineering-simulation" },
	{ label: "CATIA (CAD/CAM)", value: "catia-cad-cam" },
	{ label: "Fusion 360", value: "fusion-360" },
	{ label: "Pro Tools (Audio Production)", value: "pro-tools-audio-production" },
	{ label: "Logic Pro X", value: "logic-pro-x" },
	{ label: "Ableton Live", value: "ableton-live" },
	{ label: "Final Cut Pro", value: "final-cut-pro" },
	{ label: "DaVinci Resolve", value: "davinci-resolve" },
	{ label: "Figma (UI/UX Design)", value: "figma-ui-ux-design" },
	{ label: "Sketch (UI Design)", value: "sketch-ui-design" },
	{ label: "InVision (Prototyping)", value: "invision-prototyping" },
	{ label: "Jira (Project Management)", value: "jira-project-management" },
	{ label: "Trello", value: "trello" },
	{ label: "Asana", value: "asana" },
	{ label: "Git (Version Control)", value: "git-version-control" },
	{ label: "GitHub", value: "github" },
	{ label: "Docker (Containerization)", value: "docker-containerization" },
	{ label: "Kubernetes", value: "kubernetes" },
	{ label: "AWS (Amazon Web Services)", value: "aws-amazon-web-services" },
	{ label: "Microsoft Azure", value: "microsoft-azure" },
	{ label: "Google Cloud Platform (GCP)", value: "google-cloud-platform-gcp" },
	{ label: "Terraform (Infrastructure as Code)", value: "terraform-infrastructure-as-code" },
	{ label: "Ansible (Automation)", value: "ansible-automation" },
	{ label: "Jenkins (CI/CD)", value: "jenkins-ci-cd" },
	{ label: "Selenium (Automated Testing)", value: "selenium-automated-testing" },
	{ label: "Wireshark (Network Analysis)", value: "wireshark-network-analysis" },
	{ label: "Metasploit (Penetration Testing)", value: "metasploit-penetration-testing" },
	{ label: "Burp Suite (Web Security Testing)", value: "burp-suite-web-security-testing" },
	{ label: "Salesforce", value: "salesforce" },
	{ label: "HubSpot", value: "hubspot" },
	{ label: "Marketo (Marketing Automation)", value: "marketo-marketing-automation" },
	{ label: "QuickBooks", value: "quickbooks" },
	{ label: "Xero (Accounting Software)", value: "xero-accounting-software" },
	{ label: "Stata (Statistical Analysis)", value: "stata-statistical-analysis" },
	{ label: "SPSS (Statistical Software)", value: "spss-statistical-software" },
	{ label: "Hadoop (Big Data)", value: "hadoop-big-data" },
	{ label: "Apache Spark", value: "apache-spark" },
	{ label: "Splunk (Log Analysis)", value: "splunk-log-analysis" },
	{ label: "ServiceNow (IT Service Management)", value: "servicenow-it-service-management" },
	{ label: "ZBrush (Digital Sculpting)", value: "zbrush-digital-sculpting" },
	{ label: "Substance Painter (Texturing)", value: "substance-painter-texturing" },
	{ label: "Maya (3D Animation/Modeling)", value: "maya-3d-animation-modeling" },
	{ label: "Cinema 4D", value: "cinema-4d" },
	{ label: "Houdini (Procedural Animation)", value: "houdini-procedural-animation" },
	{ label: "Rhino (3D Modeling)", value: "rhino-3d-modeling" },
	{ label: "Grasshopper (Parametric Design)", value: "grasshopper-parametric-design" },
	{ label: "VMware (Virtualization)", value: "vmware-virtualization" },
	{ label: "Hyper-V", value: "hyper-v" },
	{ label: "LabVIEW (System Design)", value: "labview-system-design" },
	{ label: "Simulink (Simulation/Modeling)", value: "simulink-simulation-modeling" },
	{ label: "Altium Designer (PCB Design)", value: "altium-designer-pcb-design" },
	{ label: "Eagle (Electronics Design)", value: "eagle-electronics-design" },
	{ label: "Multisim (Circuit Simulation)", value: "multisim-circuit-simulation" },
	{ label: "GIMP (Open-source Image Editing)", value: "gimp-open-source-image-editing" },
	{ label: "Krita (Digital Painting)", value: "krita-digital-painting" },
	{ label: "Audacity (Audio Editing)", value: "audacity-audio-editing" },
	{ label: "Notion (Productivity/Organization)", value: "notion-productivity-organization" },
	{ label: "Slack (Team Collaboration)", value: "slack-team-collaboration" },
	{ label: "Zoom (Video Conferencing Setup/Management)", value: "zoom-video-conferencing-setup-management" },
	{ label: "Camtasia (Screen Recording/Editing)", value: "camtasia-screen-recording-editing" },
	{ label: "SAS (Data Analytics)", value: "sas-data-analytics" },
];
