name: ESLint Check Backend

on:
   push:
      branches: [main]
      paths:
         - "backend/**" # Only run if backend folder has changes
         - ".github/workflows/es-lint-backend.yml" # Run if this workflow file changes
   pull_request:
      branches: [main]
      paths:
         - "backend/**" # Only run if backend folder has changes
         - ".github/workflows/es-lint-backend.yml" # Run if this workflow file changes

jobs:
   lint:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: 18

         - name: Install dependencies in backend
           run: npm install
           working-directory: ./backend

         - name: Run ESLint
           run: npx eslint . --ext .ts,.tsx
           working-directory: ./backend
